version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - QDRANT_URL=${QDRANT_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PHOENIX_API_KEY=${PHOENIX_API_KEY}  # Arize Phoenix Key
      - PHOENIX_COLLECTOR_ENDPOINT=https://app.phoenix.arize.com/v1/traces  # Phoenix Endpoint
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}  # Added Llama Cloud API Key
    depends_on:
      - qdrant

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://backend:8000  # Ensures backend is accessible in Docker
    depends_on:
      - backend

  qdrant:
    image: qdrant/qdrant:v1.8.1
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}

volumes:
  qdrant_data:
